rails/dogFinder/config/routes.rb
Rails.application.routes.draw do
  
  root "sites#home"

  

  resources :admin_users, only: [:index, :new, :create, :edit, :update, :show, :destroy]

    resources :shelters, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      resources :dogs, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    end

  
  get "sites/what_to_expect", :to => "sites#expect"

  match ':controller(/:action(/:id))', :via => [:get, :post]

  match ':controller(/:action(/:id(.:format)))', :via => [:get, :post]

end

rails/dogFinder/app/models/shelter.rb
class Shelter < ActiveRecord::Base

    # require 'yelp'

    # client = Yelp::Client.new({ consumer_key: 758evkzvY8hmmvXw3YSi7Q,
    #                         consumer_secret: IAmFkDG1Qe011rMglJvkBWYJc_Q,
    #                         token: K6rjQtupyMqBAL_yHRobiu5cHQD1k8-m,
    #                         token_secret: 82tMJjIUEwzI_YoZsXjmjANPoXc
    #                       })

	has_attached_file :avatar, :styles => { :medium => "250x200>", :thumb => "100x100>" }, :default_url => ""
    validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

    # has_secure_password

	has_many :dogs
    belongs_to :admin_users

	validates_presence_of :address, :city, :province, :website

    validates :name, :presence => true,
                        :length => { :maximum => 50 }
    # validates :username, :length => { :within => 8..25 },
    #                    :uniqueness => true
    
    EMAIL_REGEX = /\A[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}\Z/i
    validates :email, :presence => true,
                    :length => { :maximum => 100 },
                    :format => EMAIL_REGEX,
                    :confirmation => true
end

rails/dogFinder/app/controllers/shelters_controller.rb
class SheltersController < ApplicationController

	before_action = :confirm_logged_in

	def index
     	@shelters = Shelter.order('name ASC')
  	end

	def new
		@admin_user = AdminUser.find params[:admin_user_id] 
    	@shelter = @admin_user.shelters.new 
	end

	def create
		@admin_user = AdminUser.find params[:admin_user_id]  
    	@shelter = @admin_user.shelters.new shelter_params

		if @shelter.save
			flash[:notice] = "Your shelter has been successfully added"
			redirect_to action: 'index'
		else
			render('new')
		end
	end

	def show
		@shelter = Shelter.find(params[:id])
	end

	def show_dogs
		@shelter = Shelter.find(params[:id])
		@show_dogs = @shelter.dogs
	end

	def edit
		@shelter = Shelter.find(params[:admin_user_id])
	end

	def update
		@shelter = Shelter.find(params[:id])


		if @shelter.update_attributes(shelter_params)
			flash[:notice] = "Your shelter information has been successfully updated"
			redirect_to action: 'show', id: @shelter.id
		else
			render('edit')
		end
	end

	def destroy
		@shelter = Shelter.find(params[:id]).destroy
		flash[:notice] = "#{@shelter.name} has been deleted"
		redirect_to action: 'index'
	end

	private

		def shelter_params
			params.require(:shelter).permit(:avatar, :name, :address, :city, :province, :postal_code, :phone, :website, :email, :hours, :volunteers, :admin_user_id)
		end
end

rails/dogFinder/app/helpers/shelter_helper.rb
module ShelterHelper
end

rails/dogFinder/app/views/shelters/edit.html.erb
<%= render "helpers/navbarForms" %>

<div class="formShelter">
   <%= form_for @shelter do |f| %>

	<h2>Update your shelter information:</h2>
	<br />
	<div class="formShelterName">
		<%= f.label :name %>
		<%= f.text_field :name %>
	</div> <br />
	<h3>Logo</h3>
		<%= f.file_field :avatar %>
		<br />

	<%= f.label :address %>
	<%= f.text_field :address %>
	<br />
	<%= f.label :city %>
	<%= f.text_field :city %>
	<br />
	<%= f.label :province %>
	<%= f.text_field :province %>
	<br />
	<%= f.label :postal_code %>
	<%= f.text_field :postal_code %>
	<br /><br />

	<%= f.label :phone %>
	<%= f.text_field :phone %>
	<br /><br />

	<%= f.label :website %>
	<%= f.text_field :website %>
	<br /><br />

	<%= f.label :email %>
	<%= f.text_field :email %>
	<br /><br />

	<%= f.label :hours %>
	<%= f.text_field :hours %>
	<br /><br />

	<%= f.label :volunteers %>
				<br />
					<%= f.radio_button(:volunteers, "Yes") %>
					<label for="volunteers male">Yes</label>

					<%= f.radio_button(:volunteers, "No") %>
					<label for="volunteers female">No</label>
		<br /><br />


	<%= f.submit "Update" %>

	<% end %>
	<br /><br />
	<%= link_to("<< Back to List", action: 'index') %>
</div>

rails/dogFinder/app/views/shelters/index.html.erb
<%= render "helpers/navbarForms" %>

<div class="shelterNew formShelter">
	<h2>Current List of Shelters</h2>

  <table class="shelterListings" summary="list of shelters">
    <tr class="shelterTableHeader">
      
      <th>Logo</th>
      <th>Name</th>
      <th>Street Address</th>
      <th>City</th>
      <th>Province</th>
      <th>Postal Code</th>
      <th>Phone</th>
      <th>Website</th>
      <th>Email</th>
      <th>Hours of Operation</th>

    </tr>
    <% @shelters.each do |shelter| %>
      <tr class="shelterTableDetails">
        <td><%= image_tag shelter.avatar.url :thumb %></td>
        <td><%= shelter.name %></td>
        <td><%= shelter.address %></td>
        <td><%= shelter.city %></td>
        <td><%= shelter.province %></td>
        <td><%= shelter.postal_code %></td>
        <td><%= shelter.phone %></td>
        <td><%= shelter.website %></td>
        <td><%= shelter.email %></td>
        <td><%= shelter.hours %></td>
      </tr>
    <% end %>
  </table>
    <br />
  <p>If your shelter does not appear on the list, please create a login to add your shelter to our community. <%= link_to("Click here to create your shelter's login.", controller: 'admin_users', action: 'new', class: 'actionNew') %></p>  <%= link_to( "Already a memeber?  Login here.", controller: 'access', action: 'login') %>
</div>

rails/dogFinder/app/views/shelters/new.html.erb
<%= render "helpers/navbarForms" %>

<div class="formShelter">
	<%= form_for [@admin_user, @shelter] do |f| %>

	<h2>Enter your shelter information:</h2>
	<br />
	<div class="formShelterName">
		<h3>Shelter Name</h3>
		<%= shelter.admin_user.shelter_name %>
	</div> <br />
	<%= f.label :avatar, Logo %>
	<%= f.file_field :avatar %>
		<br />

	<%= f.label :address %>
	<%= f.text_field :address %>
	<br />
	<%= f.label :city %>
	<%= f.text_field :city %>
	<br />
	<%= f.label :province %>
		<select class="form-control" id="sel1">
	      <%= render "helpers/provinces" %>
	    </select>
	<br />
	<%= f.label :postal_code %>
	<%= f.text_field :postal_code %>
	<br /><br />

	<%= f.label :phone %>
	<%= f.text_field :phone %>
	<br /><br />

	<%= f.label :website %>
	<%= f.text_field :website %>
	<br /><br />

	<%= f.label :email %>
	<%= f.text_field :email %>
	<br /><br />

	<%= f.label :hours %>
	<%= f.text_field :hours %>
	<br /><br />

	<%= f.label :volunteers %>
				<br />
					<%= f.radio_button(:volunteers, "Yes") %>
					<label for="volunteers male">Yes</label>

					<%= f.radio_button(:volunteers, "No") %>
					<label for="volunteers female">No</label>
		<br /><br />


	<%= f.submit "Create" %>

	<% end %>
	<br /><br />
	<%= link_to("<< Back to List", action: 'index') %>
</div>

rails/dogFinder/app/views/shelters/show.html.erb
<%= render "helpers/navbarForms" %>

<% if !flash[:notice].blank? %>
  <div class="shelterFLashNotice formShelter">
    <%=flash[:notice] %>
  </div>
<% end %>

<div class="shelterShow formShelter">
  
  <h2>Shelter Details</h2>

  <table class="showTable" summary="Shelter detail view">
  
    <tr>
      <th class="showListTitles">Shelter Logo</th>
      <td class="showListDetails"><%= image_tag @shelter.avatar.url :thumb %></td>
    </tr>
    <tr>
      <th class="showListTitles">Name</th>
      <td class="showListDetails"><%= @shelter.name %></td>
    </tr>
    <tr>
      <th class="showListTitles">Street Address</th>
      <td class="showListDetails"><%= @shelter.address %></td>
    </tr>
    <tr>
      <th class="showListTitles">City</th>
      <td class="showListDetails"><%= @shelter.city %></td>
    </tr>
    <tr>
      <th class="showListTitles">Province</th>
      <td class="showListDetails"><%= @shelter.province %></td>
    </tr>
    <tr>
      <th class="showListTitles">Postal Code</th>
      <td class="showListDetails"><%= @shelter.postal_code %></td>
    </tr>
    <tr>
      <th class="showListTitles">Phone</th>
      <td class="showListDetails"><%= @shelter.phone %></td>
    </tr>
    <tr>
      <th class="showListTitles">Website</th>
      <td class="showListDetails"><%= @shelter.website %></td>
    </tr>
    <tr>
      <th class="showListTitles">Email</th>
      <td class="showListDetails"><%= @shelter.email %></td>
    </tr>
    <tr>
      <th class="showListTitles">Hours of Operation</th>
      <td class="showListDetails"><%= @shelter.hours %></td>
    </tr>
    <tr>
      <th class="showListTitles">Volunteers Needed</th>
      <td class="showListDetails"><%= @shelter.volunteers %></td>
    </tr>
    <tr>
      <th class="showListTitles">Created</th>
      <td class="showListDetails"><%= @shelter.created_at %></td>
    </tr>
    <tr>
      <th class="showListTitles">Updated</th>
      <td class="showListDetails"><%= @shelter.updated_at %></td>
    </tr>
    <tr>
      <th class="showListTitles">Update Shelter Record</th>
      <td>
        <%= link_to("Edit Record", action: 'edit', id: @shelter.id, class: 'action edit') %>
      </td>
    </tr>   
    <tr>
      <th class="showListTitles">Permanently Delete Shelter Record</th>
      <td>
        <%= link_to("Delete Record", action: 'destroy', id: @shelter.id, class: 'action delete') %>
      </td>
    </tr>  
  </table>
    <br />

  <%= link_to "View Your List of Dogs", shelter_dogs_path(@shelter) %>
  <br />
  <%= link_to "Back to Shelter List", shelters_path %>


</div>